measures_2025 = {'C: Breast Cancer Screening': 1,
 'C: Colorectal Cancer Screening': 1,
 'C: Annual Flu Vaccine': 1,
 'C: Monitoring Physical Activity': 1,
 'C: Special Needs Plan (SNP) Care Management': 1,
 'C: Care for Older Adults – Medication Review': 1,
 'C: Care for Older Adults – Pain Assessment': 1,
 'C: Osteoporosis Management in Women who had a Fracture': 1,
 'C: Diabetes Care – Eye Exam': 1,
 'C: Diabetes Care – Blood Sugar Controlled':3,
 'C: Controlling Blood Pressure': 3,
 'C: Reducing the Risk of Falling': 1,
 'C: Improving Bladder Control': 1,
 'C: Medication Reconciliation Post-Discharge': 1,
 'C: Plan All-Cause Readmissions': 3,
 'C: Statin Therapy for Patients with Cardiovascular Disease': 1,
 'C: Transitions of Care': 1,
 'C: Follow-up after Emergency Department Visit for People with Multiple High-Risk Chronic Conditions': 1,
 'C: Getting Needed Care': 4,
 'C: Getting Appointments and Care Quickly': 4,
    'C: Customer Service': 4,
 'C: Rating of Health Care Quality': 4,
 'C: Rating of Health Plan': 4,
 'C: Care Coordination': 4,
 'C: Complaints about the Health Plan': 4,
 'C: Members Choosing to Leave the Plan': 4,
 'C: Health Plan Quality Improvement': 5,
 'C: Plan Makes Timely Decisions about Appeals': 4,
 'C: Reviewing Appeals Decisions': 4,
 'C: Call Center – Foreign Language Interpreter and TTY Availability': 4,
}